add ol culture question settings entities:
  title: 'Create new Ol culture question settings entities'

administer ol culture question settings entities:
  title: 'Administer Ol culture question settings entities'
  description: 'Allow to access the administration form to configure Ol culture question settings entities.'
  restrict access: true

delete ol culture question settings entities:
  title: 'Delete Ol culture question settings entities'

edit ol culture question settings entities:
  title: 'Edit Ol culture question settings entities'

view published ol culture question settings entities:
  title: 'View published Ol culture question settings entities'

view unpublished ol culture question settings entities:
  title: 'View unpublished Ol culture question settings entities'

