add ol icebreaker settings entities:
  title: 'Create new Ol icebreaker settings entities'

administer ol icebreaker settings entities:
  title: 'Administer Ol icebreaker settings entities'
  description: 'Allow to access the administration form to configure Ol icebreaker settings entities.'
  restrict access: true

delete ol icebreaker settings entities:
  title: 'Delete Ol icebreaker settings entities'

edit ol icebreaker settings entities:
  title: 'Edit Ol icebreaker settings entities'

view published ol icebreaker settings entities:
  title: 'View published Ol icebreaker settings entities'

view unpublished ol icebreaker settings entities:
  title: 'View unpublished Ol icebreaker settings entities'

