<?php

/**
 * @file
 * Contains ol_text_docs.module.
 */

/**
 * Implements hook_add_ol_section()
 * @param $sections
 */
function ol_text_docs_add_ol_section(&$sections){
  $sections['notebooks'] = array(
    'label' => t('Notebooks'),
    'path' => t('notebooks'),
    'weight' => 68,
    'icon_class' => 'lni lni-book',
  );
}

/**
 * Implements hook_theme().
 */
function ol_text_docs_theme() {
  return [
    'text_doc_item_list_page' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-item-list-page',
    ],
    'text_docs_list' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-docs-list',
    ],
    'text_doc_modal_put_in_category' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-modal-put-in-category',
    ],
    'text_doc_modal_remove_category' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-modal-remove-category',
    ],
    'text_doc_page' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-page',
    ],
    'text_doc_card' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-card',
    ],
    'text_doc_modal_remove' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-modal-remove',
    ],
  ];
}
