<?php

use Drupal\user\Entity\User;

/**
 * Implements hook_theme().
 */
function ol_members_theme() {
  return [
    'members_page' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'members-page',
    ],
    'members_card' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'members-card',
    ],
  ];
}

/**
 * Implements hook_add_ol_section()
 * @param $sections
 */
function ol_members_add_ol_section(&$sections){
  $sections['members'] = array('label' => t('Members'), 'path' => t('members'), 'weight' => 100);
}

/**
 * Implements hook_add_global_menu_item()
 * @param $sections
 */
function ol_members_add_global_menu_item(&$sections){
  $sections['members'] = array('label' => t('Everybody'), 'path' => t('members'), 'icon'=> 'lni lni-user', 'weight' => 100);
}

/**
 * Implements hook_preprocess_image_widget()
 * Used to show thumbnail after uploading file.
 *
 * @param $variables
 */
function ol_members_preprocess_image_widget(&$variables) {
  $element = $variables['element'];

  $variables['attributes'] = array('class' => array('image-widget', 'js-form-managed-file', 'form-managed-file', 'clearfix'));

  if (!empty($element['fids']['#value'])) {
    $file = reset($element['#files']);
    $element['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">(' . format_size($file->getSize()) . ')</span> ';
    $file_variables = array(
      'style_name' => $element['#preview_image_style'],
      'uri' => $file->getFileUri(),
    );

    // Determine image dimensions.
    if (isset($element['#value']['width']) && isset($element['#value']['height'])) {
      $file_variables['width'] = $element['#value']['width'];
      $file_variables['height'] = $element['#value']['height'];
    } else {
      $image = \Drupal::service('image.factory')->get($file->getFileUri());
      if ($image->isValid()) {
        $file_variables['width'] = $image->getWidth();
        $file_variables['height'] = $image->getHeight();
      }
      else {
        $file_variables['width'] = $file_variables['height'] = NULL;
      }
    }

    $element['preview'] = array(
      '#weight' => -10,
      '#theme' => 'image_style',
      '#width' => $file_variables['width'],
      '#height' => $file_variables['height'],
      '#style_name' => $file_variables['style_name'],
      '#uri' => $file_variables['uri'],
    );

    // Store the dimensions in the form so the file doesn't have to be
    // accessed again. This is important for remote files.
    $element['width'] = array(
      '#type' => 'hidden',
      '#value' => $file_variables['width'],
    );
    $element['height'] = array(
      '#type' => 'hidden',
      '#value' => $file_variables['height'],
    );
  }

  $variables['data'] = array();
  foreach (\Drupal\Core\Render\Element::children($element) as $child) {
    $variables['data'][$child] = $element[$child];
  }
}
