add ol social question settings entities:
  title: 'Create new Ol social question settings entities'

administer ol social question settings entities:
  title: 'Administer Ol social question settings entities'
  description: 'Allow to access the administration form to configure Ol social question settings entities.'
  restrict access: true

delete ol social question settings entities:
  title: 'Delete Ol social question settings entities'

edit ol social question settings entities:
  title: 'Edit Ol social question settings entities'

view published ol social question settings entities:
  title: 'View published Ol social question settings entities'

view unpublished ol social question settings entities:
  title: 'View unpublished Ol social question settings entities'

