<?php

/**
 * @file
 * Contains ol_files.module.
 */

/**
 * Implements hook_add_ol_section()
 * @param $sections
 */
function ol_files_add_ol_section(&$sections){
  $sections['files'] = array('label' => t('Docs & Files'), 'path' => t('files'), 'weight' => 100);
}

/**
 * Implements hook_theme().
 */
function ol_files_theme() {
  return [
    'file_item_list_page' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'file-item-list-page',
    ],
    'files_list' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'files-list',
    ],
    'file_modal_put_in_folder' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'file-modal-put-in-folder',
    ],
    'file_modal_remove_folder' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'file-modal-remove-folder',
    ],
    'text_doc_page' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-page',
    ],
    'text_doc_card' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'text-doc-card',
    ],
  ];
}
