<?php

/**
 * @file
 * Contains lus_message.module.
 */

/**
 * Implements hook_theme().
 */
function ol_messages_theme() {
  return [
    'message_page' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'message-page',
    ],
    'messages_list' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'messages-list',
    ],
    'message_card' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'message-card',
    ],
    'message_card_list' => [
      'variables' => [
        'vars' => NULL,
      ],
      'template' => 'message-card-list',
    ],
  ];
}

/**
 * Implements hook_add_ol_section()
 * @param $sections
 */
function ol_messages_add_ol_section(&$sections){
  $sections['messages'] = array(
    'label' => t('Messages'),
    'path' => 'messages',
    'weight' => 60,
    'icon_class' => 'lni lni-envelope',
    );
}


